# https://docs.travis-ci.com/user/getting-started/
# https://docs.travis-ci.com/user/customizing-the-build/
# http://lint.travis-ci.org/
language: python

python:
- 2.7
- 3.5

install:
- pip install numpy matplotlib scipy scikit-learn pytest coveralls Sphinx
# use coverage to run "pytest -s" as the main module (-m) using skpp as the code to measure (--source)

script:
  - coverage run --source=skpp -m pytest -s
  - sphinx-build -b html doc skpp

after_success:
  - coveralls

notifications:
  email:
  - pvlkmrv@gmail.com

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 928174cee70fd38420956befdd90fd12933b15a6
  keep-history: true
  on:
    branch: master

#  provider: pypi
#  user: pavelkomarov
#  password:
#    secure: L12e2JIGYwgiK+0s1pp2A/OsdZmRQALXbMTEjOWTNurWhTxXZZJ9R+M6U2M9ZmkxZ6we3maZ3Bcuv10zzvi/LoE0VIgaaL+kLHYkq1hPe83wxdmEepk4/uzIABy6XKunx59ennMJSaMZM+9Ks5VzZ1GuVhKhpt13FQQbbKX4uw9lywalzkuKbyD20boaJeJfKAkXguQAzquZB1+n1cpeKO/2qkMQ+2M6iSIT+kM0qPZrS6xJ5ENrjxlDqIuDLlw/XZqRUyEdm9SKDYycq9Imw5aOFI2uTyrjowBlTRNTqbclo6NOak4YQ5zGzk0Rqq2tQKXgamEhmF5JwACQo1DsJapK7ihJC+blSIlkDSvrmUivgjJmF8GdFzgSumek60MRwqqs9t9PdmV/p3rzm+nlcstpwh3s7DVMTLMGkXXqdr2CJAQXFb0QRag6chURAPRSA4N6Z8bm45LURwJq5mHetm9tbxQHoWwV1/SIjQ2wgAeTZNog1jCk/4LSdDCTrAx1/0MVjVUOIY+hlH4UvZDS61CSeDEZUH4HTttz+Zbf01byu63LyC6mg7WwTMRHGc8T36c/XPrKzgSVkLqeDOZVani9hakUvcHT5EyMYXUZmECQ7GTHRB4Ttf2wREPSIRX1FdOnm10+JUb9YqRkVHbvb/ye+1l1DNLcmBNGOLyQb9M=
#  on:
#    tags: true
#    branch: master
#    python: '3.5'
